---
id: rubykaigi-2018
base_name: my-way-with-ruby
tags:
- rabbit
- rubykaigi
presentation_date: 2018-06-01
version: 2018.6.1.5
licenses:
- CC-BY-SA-4.0
slideshare_id: rubykaigi2018mywaywithruby-99853205
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: d7lDhsE1jXg
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: 
